In [2]:
import pandas as pd
import sys
import numpy as np

In [3]:
input_data=pd.read_csv('/home/anu/Downloads/movie.csv',index_col=0,na_values=['?'])
input_data
input_data.fillna(input_data.mean(),inplace=True)
input_data

,"I, Robot",The Martian,Do Androids Dream of Electric Sheep?,2001 Space Odyssey,Solaris
User,,,,,
Alice,8,2.0,10,5,1.0
Bob,4,5.5,2,10,9.0
Carl,3,8.0,4,9,10.0
Daniel,5,10.0,4,9,10.0
Eve,7,2.0,9,6,7.5

In [5]:
def movie_recom(user,movie,input_data,S=2):
    try:
        uindx=input_data.index.get_loc(user)
        print(uindx)
        bindx=input_data.columns.get_loc(movie)
        print(bindx)
    except:
        print('User Does not exist',sys.exc_info()[0])
        sys.exit(1)
        
    U,s,V=np.linalg.svd(input_data)
    print(U)
    print()
    print(s)
    print()
    print(V)
    print()
    
    reduced_sigma=np.mat(np.eye(S)*s[:S])
    U_reduced=U[:,:S]
    V_reduced=V[:S,:]
    
    print("reduced matrices")
    print(U_reduced)
    print()
    print(reduced_sigma)
    print()
    print(V_reduced)
    print()
    
    print('matrix w.r.t input index')
    print(U_reduced[uindx,:])
    print()
    print(reduced_sigma)
    print()
    print(np.mat(V_reduced[:,bindx]).T)
    
    recommended=U_reduced[uindx,:]*reduced_sigma*np.mat(V_reduced[:,bindx]).T
    
    return recommended.item(0)

bob_val=movie_recom('Bob','The Martian',input_data)
print()
print('Bob Score: %.2f'%bob_val)
print()

1
1
[[-0.31969569  0.74453556 -0.44167611  0.34228456 -0.17670586]
 [-0.44530343 -0.28423876  0.37671463  0.75116438  0.12145513]
 [-0.48746723 -0.29970649 -0.0399786  -0.25655953 -0.77790143]
 [-0.53317843 -0.28367474 -0.51241193 -0.25604694  0.55418714]
 [-0.42142139  0.44111199  0.63154099 -0.43267832  0.2043763 ]]

[32.79398239 12.04625881  3.72635956  2.75357416  1.21426569]

[[-0.34814384 -0.40138233 -0.36479067 -0.54174122 -0.53956678]
 [ 0.46401295 -0.36745163  0.70672241 -0.1430709  -0.36020194]
 [-0.07722253 -0.80300569 -0.05072648  0.1010361   0.58003195]
 [ 0.24124006 -0.24053433 -0.37019394  0.73124537 -0.46063339]
 [ 0.77416262  0.03459211 -0.47734105 -0.3756582   0.17464842]]

reduced matrices
[[-0.31969569  0.74453556]
 [-0.44530343 -0.28423876]
 [-0.48746723 -0.29970649]
 [-0.53317843 -0.28367474]
 [-0.42142139  0.44111199]]

[[32.79398239  0.        ]
 [ 0.         12.04625881]]

[[-0.34814384 -0.40138233 -0.36479067 -0.54174122 -0.53956678]
 [ 0.46401295 -0.36745163  0.70672241 -0.1430709  -0.36020194]]

matrix w.r.t input index
[-0.44530343 -0.28423876]

[[32.79398239  0.        ]
 [ 0.         12.04625881]]

[[-0.40138233]
 [-0.36745163]]

Bob Score: 7.12

In [6]:
bob_val=movie_recom('Eve','Solaris',input_data)
print()
print('Eve Score: %.2f'%bob_val)
print()

4
4
[[-0.31969569  0.74453556 -0.44167611  0.34228456 -0.17670586]
 [-0.44530343 -0.28423876  0.37671463  0.75116438  0.12145513]
 [-0.48746723 -0.29970649 -0.0399786  -0.25655953 -0.77790143]
 [-0.53317843 -0.28367474 -0.51241193 -0.25604694  0.55418714]
 [-0.42142139  0.44111199  0.63154099 -0.43267832  0.2043763 ]]

[32.79398239 12.04625881  3.72635956  2.75357416  1.21426569]

[[-0.34814384 -0.40138233 -0.36479067 -0.54174122 -0.53956678]
 [ 0.46401295 -0.36745163  0.70672241 -0.1430709  -0.36020194]
 [-0.07722253 -0.80300569 -0.05072648  0.1010361   0.58003195]
 [ 0.24124006 -0.24053433 -0.37019394  0.73124537 -0.46063339]
 [ 0.77416262  0.03459211 -0.47734105 -0.3756582   0.17464842]]

reduced matrices
[[-0.31969569  0.74453556]
 [-0.44530343 -0.28423876]
 [-0.48746723 -0.29970649]
 [-0.53317843 -0.28367474]
 [-0.42142139  0.44111199]]

[[32.79398239  0.        ]
 [ 0.         12.04625881]]

[[-0.34814384 -0.40138233 -0.36479067 -0.54174122 -0.53956678]
 [ 0.46401295 -0.36745163  0.70672241 -0.1430709  -0.36020194]]

matrix w.r.t input index
[-0.42142139  0.44111199]

[[32.79398239  0.        ]
 [ 0.         12.04625881]]

[[-0.53956678]
 [-0.36020194]]

Eve Score: 5.54